[metadata]
name = ud2
version = 0.1.0

description = Tools for working with UDv2
long_description = file: README.md
long_description_content_type = text/markdown

author = Christopher O'Brien
# O'Brien breaks a lot of tools.
author_email = cobrien@redhat.com
url = https://gitlab.cee.redhat.com/cobrien/ud2

license = GNU General Public License v3 (GPLv3)
license_files = LICENSE

classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Operating System :: OS Independent
    Intended Audience :: Developers


[options]
packages = find:
python_requires = >=3.7
include_package_data = True
install_requires =
    click
    pydantic
    PyYAML
    requests

[options.packages.find]
exclude = tests

[options.entry_points]
console_scripts =
    ud2 = ud2.cli:main


[tox:tox]
min_version = 4.0
env_list = py,flake8,build


[testenv]
use_develop = true
deps =
    click>=8.1
commands =
    python -Bm unittest discover -s tests -t .

[testenv:flake8]
deps = flake8
commands =
    python -Bm flake8 src tests

[testenv:build]
deps =
    build
commands =
    python -Bm build --sdist --wheel --no-isolation


[flake8]
max-line-length = 100
select = C,E,F,W,B,B950
ignore =
    E203
    E266
    E501
    W503


# The end.
