[metadata]
name = ud2
version = 0.1.0

description = Tools for working with UDv2
long_description = file: README.md
long_description_content_type = text/markdown

author = Christopher O'Brien
# O'Brien breaks a lot of tools.
author_email = cobrien@redhat.com
url = https://gitlab.cee.redhat.com/spmm/ud2

license = GNU General Public License v3 (GPLv3)
license_files =
    LICENSE

classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Operating System :: OS Independent
    Intended Audience :: Developers

copyright_years = 2025


[options]
packages = find:
python_requires = >=3.7
include_package_data = True
install_requires =
    click
    pydantic
    PyYAML
    requests

[options.packages.find]
exclude = tests

[options.entry_points]
console_scripts =
    ud2 = ud2.cli:main


[tox:tox]
min_version = 4.0
env_list = py, docs


[testenv]
use_develop = true
deps =
    pytest
    pydantic>=2.0.0
    importlib-metadata; python_version < "3.8"
commands =
    python -Bm pytest {posargs:tests}


[testenv:compat]
deps =
    pytest
    pydantic<2.0.0
    importlib-metadata; python_version < "3.8"
commands =
    python -Bm pytest {posargs:tests}


[testenv:py-cover]
description = Run unit tests with coverage using the default dependencies.
use_develop = true
deps =
    {[testenv]deps}
    coverage
commands =
    coverage run --branch --data-file=.coverage.py -m pytest {posargs:tests}


[testenv:compat-cover]
description = Run unit tests with coverage under the compat dependency set.
use_develop = true
deps =
    {[testenv:compat]deps}
    coverage
commands =
    coverage run --branch --data-file=.coverage.compat -m pytest {posargs:tests}


[testenv:coverage-report]
description = Combine coverage data and emit terminal, XML, and HTML reports.
skip_install = true
deps = coverage
commands =
    coverage combine .coverage.py .coverage.compat
    coverage report
    coverage xml
    coverage html


[testenv:flake8]
deps = flake8
commands =
    python -Bm flake8 ud2


[testenv:build]
deps =
    setuptools
    build
commands =
    python -Bm build --sdist --wheel --no-isolation


[testenv:docs]
description = Build Sphinx HTML documentation
deps =
    sphinx
    myst-parser
    linkify-it-py
    sphinxcontrib-mermaid
    sphinx_rtd_theme
commands =
    sphinx-build -W --keep-going -b html docs build/docs {posargs}


[flake8]
max-line-length = 100
select = C,E,F,W,B,B950
ignore =
    E203,E266,E303,E501
    W503


[coverage:run]
branch = True
source =
    ud2

# omit =
#     */.tox/*
#     */.venv/*


[coverage:report]
skip_covered = False
show_missing = True


[coverage:html]
directory = build/coverage-html


[coverage:xml]
output = build/coverage.xml


# The end.
